// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/wiki/WikiIndex.tsx": () => import("../components/mockups/wiki/WikiIndex.tsx"),
  "./components/mockups/wiki/WikiPage.tsx": () => import("../components/mockups/wiki/WikiPage.tsx")
};
